//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOnline
    {
        public int ID { get; set; }
        public Nullable<int> FK_Userid { get; set; }
        public Nullable<System.DateTime> OnlineDate { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.DateTime> OffineDate { get; set; }
        public string ConnectId { get; set; }
    
        public virtual UserOnline UserOnline1 { get; set; }
    }
}
